print('Hello world')
print('What is your name?')
myName = input()
print(f"It's good to meet you, {myName}")
print("The length of your name is:")
print(len(myName))
print("What is your age?")
myAge = int(input())
print(f"You will be {str(myAge + 1)} in a year")